apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-postgres-config
  labels:
    app: accounts
data:
  POSTGRES_DB: accounts
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: root
  POSTGRESQL_DATABASE: accounts