apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: accounts-postgres
spec:
  selector:
    matchLabels:
      app: accounts-postgres
  serviceName: accounts-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: accounts-postgres
    spec:
      containers:
      - name: postgres
        image: centos/postgresql-96-centos7
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: accounts-postgres-secrets
                key: postgresql_user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: accounts-postgres-secrets
                key: postgresql_password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: accounts-postgres-secrets
                key: postgresql_database
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: accounts-postgres-pv-claim