kind: PersistentVolume
apiVersion: v1
metadata:
  name: accounts-postgres-pv-volume
  labels:
    type: local
    app: accounts
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data/accounts"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: accounts-postgres-pv-claim
  labels:
    app: accounts
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi