kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: accounts-postgres-pv-claim
  labels:
    app: accounts
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi